$(".reni-btn").click(function(){
    $(".reni-cover").addClass("reveal");
    $(".vinyl2").addClass("reveal");
    $(".vinyl2").removeAttr("style");
    $('.rep-cover').hide(); 
    $('.mbf-cover').hide(); 
    $('.folk-cover').hide(); 
    $('.bday-cover').hide(); 
    $('.sunshine-cover').hide(); 
});
$(".rep-btn").click(function(){
    $(".rep-cover").addClass("reveal");
    $(".draggable").removeAttr("style");
    $('.reni-cover').hide(); 
    $('.mbf-cover').hide(); 
    $('.folk-cover').hide(); 
    $('.bday-cover').hide(); 
    $('.sunshine-cover').hide();
});
$(".mbf-btn").click(function(){
    $(".mbf-cover").addClass("reveal");
    $(".draggable").removeAttr("style");
    $('.rep-cover').hide(); 
    $('.reni-cover').hide(); 
    $('.folk-cover').hide(); 
    $('.bday-cover').hide(); 
    $('.sunshine-cover').hide();
});
$(".folk-btn").click(function(){
    $(".folk-cover").addClass("reveal");
    $(".draggable").removeAttr("style");
    $('.rep-cover').hide(); 
    $('.mbf-cover').hide(); 
    $('.reni-cover').hide(); 
    $('.bday-cover').hide(); 
    $('.sunshine-cover').hide();
});
$(".bday-btn").click(function(){
    $(".bday-cover").addClass("reveal");
    $(".draggable").removeAttr("style");
    $('.rep-cover').hide(); 
    $('.mbf-cover').hide(); 
    $('.folk-cover').hide(); 
    $('.reni-cover').hide(); 
    $('.sunshine-cover').hide();
});
$(".sunshine-btn").click(function(){
    $(".sunshine-cover").addClass("reveal");
    $(".draggable").removeAttr("style");
    $('.rep-cover').hide(); 
    $('.mbf-cover').hide(); 
    $('.folk-cover').hide(); 
    $('.bday-cover').hide(); 
    $('.reni-cover').hide();
});

$(".draggable").draggable();